In [1]:
import numpy as np

In [7]:
#single dimentional array


In [2]:
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [6]:
#multidimentional array

In [5]:
n2 = np.array([[10,20,30,40],[40,30,20,10],[20,40,60,80]])
n2


array([[10, 20, 30, 40],
       [40, 30, 20, 10],
       [20, 40, 60, 80]])

In [8]:
#array comprising of only zeroes

In [13]:
n3 =np.zeros((10,10))
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
#array comprising of particular value 69

In [14]:
n4 =np.full((4,4),69)
n4

array([[69, 69, 69, 69],
       [69, 69, 69, 69],
       [69, 69, 69, 69],
       [69, 69, 69, 69]])

In [16]:
#arranged array in a particular range

In [22]:
n5 = np.arange(10,50,5)
n5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
n5 = np.arange(100,300,5)
n5

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160,
       165, 170, 175, 180, 185, 190, 195, 200, 205, 210, 215, 220, 225,
       230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290,
       295])

In [24]:
#random numbers generation through array


In [25]:
n7=np.random.randint(1,10,5)
n7

array([5, 9, 8, 1, 7])