In [5]:
#we will learn numpy in details

In [6]:
import numpy as np

In [81]:
x1= np.arange(10)
x1
#np.arrange is used to produce an array in a particular range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x1[0:10:2] #to produce an alternative even series. The command is array[start:stop:step]

array([0, 2, 4, 6, 8])

In [18]:
x1[1:10:2] #to produce an alternartive odd series 


array([1, 3, 5, 7, 9])

In [19]:
#reversed array 

x1[10::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
#reversed array from index 5
x1[5::-1]

array([5, 4, 3, 2, 1, 0])

In [27]:
#reversed alternating odd series 
x1[10:0:-2]
#similarly for an alternating even series replace with 8:0:-2  

array([9, 7, 5, 3, 1])

In [33]:
#code to generate a randon 2 dimentional array

x2 = np.random.randint(10, size=(4, 4))
x2

array([[3, 2, 2, 4],
       [5, 4, 3, 7],
       [1, 2, 9, 8],
       [6, 6, 8, 9]])

In [35]:
x2[:4]

array([[3, 2, 2, 4],
       [5, 4, 3, 7],
       [1, 2, 9, 8],
       [6, 6, 8, 9]])

In [40]:
x2[:4,:2] #slicing particular coloumns

array([[3, 2],
       [5, 4],
       [1, 2],
       [6, 6]])

In [41]:
x2[::-1,::-1] #reversing the array the every possible way

array([[9, 8, 6, 6],
       [8, 9, 2, 1],
       [7, 3, 4, 5],
       [4, 2, 2, 3]])

In [44]:
x2[0,:] #accessing a particular row  

array([3, 2, 2, 4])

In [45]:
x2[:,0] #accessing a particular coloumn 

array([3, 5, 1, 6])

In [47]:
#constructing 3x3  sub array from the main array

x2sub = x2[:3,:3]
x2sub


array([[3, 2, 2],
       [5, 4, 3],
       [1, 2, 9]])

In [61]:
x2[2,3] #accessing a particular number form array
#remember that the rows and coloums in computers start from 0 not 1 unlike maths :\

8

In [62]:
x3 = x2.copy() #creating copies of arrays using the .copy() method

In [63]:
x3


array([[3, 2, 2, 4],
       [5, 4, 3, 7],
       [1, 2, 9, 8],
       [6, 6, 8, 9]])

In [67]:
#reshaping arrays 

mat33= np.arange(1,10).reshape((3,3))
mat33
# this matrix was originally a (1x9) matrix but we changed it into (3x3) matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
# now we will learn a very important concept of .reshape and np.newaxis method used for array trasformation 
x4 = np.array([1,2,3])
x5 = x4[:,np.newaxis]
x5  #it is the coloumn transformation


array([[1],
       [2],
       [3]])

In [76]:
x6 = x4[np.newaxis,:]
x6

array([[1, 2, 3]])

In [78]:
#doing the same using reshape method

x7 = x4.reshape((3,1))
x7

array([[1],
       [2],
       [3]])

In [79]:
x8 = x4.reshape(1,3)
x8

array([[1, 2, 3]])

In [90]:
x9 = np.random.randint(3,10, size=(4, 4))
x9

array([[9, 5, 5, 6],
       [6, 6, 7, 3],
       [8, 7, 4, 5],
       [7, 5, 9, 3]])

In [96]:
#next is concatenation of arrays which is basically joing two arrays
#we can concatenate as many arrays as we like just like we did with 3 arrays 

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
d = np.concatenate([a,b,c])
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
