In [2]:
#checking the dimentionality of the arrays(useful in matrix )

In [1]:
import numpy as np

In [6]:
a1 = np.array([[1,2,3],[3,4,5],[7,8,9]])
a1.shape

(3, 3)

In [9]:
a1.shape= (3,3)
a1

array([[1, 2, 3],
       [3, 4, 5],
       [7, 8, 9]])

In [10]:
a2= np.array([[1,2],[3,4],[5,6],[7,8]])
a2.shape = (2,4)
a2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a2.shape = (4,2)
a2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
a3=a2

In [14]:
a3.shape = (2,4)
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
a4 = a2*a3

In [16]:
a4


array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [17]:
a5 = a3+a4
a6 = a4-a3
a5
a6

array([[ 0,  2,  6, 12],
       [20, 30, 42, 56]])

In [18]:
a6

array([[ 0,  2,  6, 12],
       [20, 30, 42, 56]])

In [19]:
a5

array([[ 2,  6, 12, 20],
       [30, 42, 56, 72]])

In [20]:
a7=a5+a6
a7

array([[  2,   8,  18,  32],
       [ 50,  72,  98, 128]])

In [21]:
a8=a7/2
a8

array([[ 1.,  4.,  9., 16.],
       [25., 36., 49., 64.]])

In [22]:
#adding numpy arrays using the np.sum method

In [23]:
n1 = np.array([10,20])
n2 = np.array([30,40])
n3 = np.sum([n1,n2],axis = 1)

In [24]:
n3


array([30, 70])

In [25]:
n4= np.sum([n1,n2])
n4

100

In [26]:
n5 = np.sum([n1,n2],axis=0)

In [27]:
n5

array([40, 60])

In [29]:
n6=np.array([n1,n2])

In [30]:
n6

array([[10, 20],
       [30, 40]])

In [36]:
b1=np.array([[3,4],[5,6],[13,14]])
b1

array([[ 3,  4],
       [ 5,  6],
       [13, 14]])

In [38]:
b2 =np.array([[7,8],[9,10],[11,12]])
b2.shape=(3,2)

In [39]:
b3=b2*b1

In [40]:
b3

array([[ 21,  32],
       [ 45,  60],
       [143, 168]])

In [41]:
b4=np.sum([b1,b2,b3])

In [42]:
b4

571